disabled_rules:
  - force_cast
  - type_name
  - identifier_name
  - control_statement
  - nesting
  - notification_center_detachment
  - private_over_fileprivate
  - statement_position
  - trailing_whitespace
  - file_name
  - trailing_newline
  - unavailable_function
  - unused_optional_binding
  - valid_ibinspectable

opt_in_rules:
  - closure_body_length
  - closure_spacing
  - closure_end_indentation
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - collection_alignment

  - discouraged_object_literal

  - empty_count
  - explicit_init

  - fallthrough
  - fatal_error_message
  - file_name
  - first_where
  - function_default_parameter_at_end

  - identical_operands

  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent

  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters

  - nimble_operator - discuss

  - operator_usage_whitespace
  - overridden_super_call

  - private_outlet
  - prohibited_super_call

  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case

  - sorted_first_last
  - static_operator
  - switch_case_on_newline

  - toggle_bool

  - unavailable_function

  - vertical_parameter_alignment_on_call

excluded:
  - Carthage
  - Pods
  - Generated
  - R.generated.swift
  - XcodeTemplates

line_length: 
  - 256 # warning
  - 512 # error

cyclomatic_complexity:
  ignores_case_statements: true

type_body_length:
  - 500 # warning
  - 700 # error

file_length:
  warning: 500
  error: 1200

function_parameter_count:
  error: 5

identifier_name:
  excluded:
    - id
    - ok
    - URL
    - x
    - y
    - z

custom_rules:
  zero:
    name: "Short .zero"
    regex: '\(top: 0, left: 0, bottom: 0, right: 0\)'
    message: "Please use short init `.zero`."
    severity: error

  let_variable:
    name: "Let Variable"
    regex: 'var\s\w*(:|(\s=))\sVariable'
    message: "Please make variable using `let`."
    severity: error

  marks_style:
    name: "Marks"
    regex: '// MARK: -?[a-zA-Z0-9]'
    message: "Marks should follow the following structure: // MARK: - Comment."
    severity: warning

  unnecessary_type:
   name: "Unnecessary Type"
   regex: '[ @a-zA-Z]*(?:let|var)\s\w*: ([a-zA-Z0-9]*)\?? = \1'
   message: "Type definition not needed"
   severity: error

  unowned:
    name: "Unowned"
    regex: 'unowned'
    message: "Please use `weak` instead. "
    severity: error

  if_else_syntax:
   name: "If-else structure syntax"
   regex: '} else'
   message: "Alternative code execution flow MUST have new line at the beginning"
   severity: warning

  continue_keyword:
    name: "Continue"
    regex: 'continue'
    message: "Don't use continue instruction"
    severity: warning
    match_kinds: keyword
