platform :ios, '12.0'

use_frameworks!
inhibit_all_warnings!

target 'ClubhouseAvatarMaker' do
  
  pod 'SwiftLint'
  pod 'R.swift'
  pod 'DKImagePickerController'
  pod 'CropViewController'
  pod 'ISEmojiView', :path => '../ISEmojiViewPod'

#  Exclude DEPLOYMENT_TARGET warnings
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
    end
  end

  target 'ClubhouseAvatarMakerTests' do
      inherit! :search_paths
  end
end
